version: '2.2'
services:
  nginx:
    command: /bin/bash -c "useradd -ms /bin/bash myuser && echo 'myuser ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers && su myuser"
    depends_on:
      - api
      - client
    restart: always
    build: 
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"

  api:
    command: /bin/bash -c "useradd -ms /bin/bash myuser && echo 'myuser ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers && su myuser"
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    
  client:
    command: /bin/bash -c "useradd -ms /bin/bash myuser && echo 'myuser ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers && su myuser"
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    
  # mongo:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=example